export const Productitems=[
    {
       "new":"new",
     "image":"http://localhost:3000/static/media/product-1.77df83befd34da1ae66b.webp",
     "hoverimage":"http://localhost:3000/static/media/product-15.8402aa2e613a89978c71.webp",
     "productcategory":"Fresh Mango",
     "productname":"Juicy Couture Juicy Quilted Ter..",
     "ratestars":4,
     "discountprice":18.90,
     "orgnalprice":34.21
},
 {
       "new":"new",
     "image":"http://localhost:3000/static/media/product-2.be27eda3a886d1e603a5.webp",
      "hoverimage":"http://localhost:3000/static/media/product-15.8402aa2e613a89978c71.webp",
      "productcategory":"Fresh Juice",
     "productname":"New Balance Fresh Foam Ka..",
           "ratestars":3,
      "discountprice":15.12,
     "orgnalprice":18.90,
   
},
 {
       "new":"new",
     "image":"http://localhost:3000/static/media/product-3.8bde60115102cc279829.webp",
     "hoverimage":"http://localhost:3000/static/media/product-4.2f7bea4078eaff9324bf.webp",
      "productcategory":"GRAPHIC CORNER",
     "productname":"Brixton Patrol All Terrain Ano..",
    "ratestars":5,
     "orgnalprice":18.90
 },
 {
       "new":"new",
     "image":"http://localhost:3000/static/media/product-5.f16a21f9b0ec4427f871.webp",
     "hoverimage":"http://localhost:3000/static/media/product-15.8402aa2e613a89978c71.webp",
     "productcategory":"GRAPHIC CORNER",
     "productname":"Juicy Couture Tricot Logo Strip..",
           "ratestars":5,
     "orgnalprice":18.90,
},
 {
       "new":"new",
     "image":"http://localhost:3000/static/media/product-6.b71a386fe46abf32e458.webp",
     "hoverimage":"http://localhost:3000/static/media/product-15.8402aa2e613a89978c71.webp",
     "icon":"",
     "studiodesign":"STUDIO DESIGN",
     "productname":"New Balance Arishi Sport v1",
     "ratestars":4,
     "orgnalprice":18.90,
 },

 {
       "new":"new",
     "image":"http://localhost:3000/static/media/product-7.f9b283f78a0156ea1562.webp",
     "hoverimage":"http://localhost:3000/static/media/product-8.bbdf080b3c3e747ba680.webp",
     "productcategoryn":"GRAPHIC CORNAR",
     "productname":"Fila Locker Room Varsity Jacket",
    "ratestars":5,
     "orgnalprice":18.90,
},

 {
       "new":"new",
     "image":"http://localhost:3000/static/media/product-9.8e7cab14ed958836ba92.webp",
     "hoverimage":"http://localhost:3000/static/media/product-15.8402aa2e613a89978c71.webp",
     "productcategory":"Studio design",
     "productname":"Water And Wind Resistant Ins..",
     
     "orgnalprice":18.90,
    }, {
       "new":"new",
     "image":"http://localhost:3000/static/media/product-10.396b7bb2b5c2f2331cf2.webp",
     "hoverimage":"http://localhost:3000/static/media/product-15.8402aa2e613a89978c71.webp",
     "productcategory":"STUDIO DESIGN",
     "productname":"New Luxury Men's Slim Fit Shi..",
           "ratestars":3,
     "orgnalprice":29.00,
   
},

 {
       "new":"new",
     "image":"http://localhost:3000/static/media/product-11.fc223d285a07e560948c.webp",
    "hoverimage":"http://localhost:3000/static/media/product-12.4898eacf736bc9c9f196.webp",
     "productcategory":"Studio design",
     "productname":"Originals Kaval Windbreaker..",
         "ratestars":3,
     "discountprice":21.51,
     "orgnalprice":23.90
    
},

 {
       "new":"new",
     "image":"http://localhost:3000/static/media/product-4.2f7bea4078eaff9324bf.webp",
     "hoverimage":"http://localhost:3000/static/media/product-3.8bde60115102cc279829.webp",
     "productcategory":"STUDIO DESIGN",
     "productname":"Brixton Patrol All Terrain Anor..",
        "ratestars":5,
     "orgnalprice":18.90
   
},
 {
       "new":"new",
     "image":"http://localhost:3000/static/media/product-14.8a657db814e2a91754b0.webp",
     "hoverimage":"http://localhost:3000/static/media/product-15.8402aa2e613a89978c71.webp",
     "studiodesign":"STUDIO DESIGN",
     "productname":"Madden By Steve Madden Cale 6",
         "ratestars":5,
     "discountprice":10.12,
     "orgnalprice":11.90
   
},
 {
    "new":"new",
     "image":"http://localhost:3000/static/media/product-15.8402aa2e613a89978c71.webp",
    "hoverimage":"http://localhost:3000/static/media/product-2.be27eda3a886d1e603a5.webp",
    "studiodesign":"STUDIO DESIGN",
     "productname":"Madden By Steve Madden Cale 6",
     "ratestars":"3",
     "discountprice":10.12,
     "orgnalprice":35.90
}

]

export const regFormFullData = [
  {
    valid: true,
    radioOption: [
      {
        value: "1",
        label: "Student",
      },
      {
        value: "2",
        label: "Employeer",
      },
    ],
    sno: 0,
    errorMessage: "",
    inputType: "radio",
    typeuser: "default",
    label: "Choose user type",
    value: "1",
    required: true,
  },
  {
    valid: true,
    sno: 1,
    errorMessage: "",
    inputType: "text",
    typeuser: "default",
    label: "Full Name",
    placeholder: "Full Name",
    value: "",
    required: true,
    helpertext: "Max 30 characters allowed",
    maxCharacters: 30
  },
  {
    valid: true,
    sno: 2,
    errorMessage: "",
    inputType: "text",
    typeuser: "default",
    label: "User ID",
    placeholder: "Enter User ID",
    value: "",
    required: true,
    helpertext: "Max 30 characters allowed",
    maxCharacters: 30
  },
  {
    valid: true,
    sno: 3,
    errorMessage: "",
    inputType: "text",
    typeuser: "default",
    label: "Password",
    placeholder: "***",
    value: "A123%b123",
    required: true,
    helpertext: "Max 30 characters allowed",
    maxCharacters: 30
  },
  {
    valid: true,
    sno: 4,
    errorMessage: "",
    inputType: "text",
    typeuser: "default",
    label: "Email ID",
    placeholder: "Enter Email ID",
    value: "",
    required: true,
    helpertext: "Max 50 characters allowed",
    maxCharacters: 50
  },
  {
    valid: true,
    sno: 5,
    errorMessage: "",
    inputType: "phone num",
    typeuser: "default",
    label: "Phone number",
    value: "",
    required: true,
  },
  {
    valid: true,
    sno: 6,
    errorMessage: "",
    inputType: "select",
    typeuser: "default",
    label: "Country",
    placeholder: "",
    value: "",
    required: true,
  },
  {
    valid: true,
    sno: 7,
    errorMessage: "",
    inputType: "select",
    typeuser: "default",
    label: "State",
    placeholder: "",
    value: "",
    required: false,
  },

  {
    valid: true,
    radioOption: [
      {
        value: "male",
        label: "Male",
      },
      {
        value: "female",
        label: "Female",
      },
    ],
    sno: 8,
    errorMessage: "",
    inputType: "radio",
    typeuser: "1",
    label: "Choose gender",
    value: "",
    required: false,
  },
  {
    valid: true,
    sno: 9,
    errorMessage: "",
    inputType: "date",
    typeuser: "1",
    label: "Date of birth",
    value: "",
    required: false,
    placeholder: "Enter Your DOB",
  },
  {
    valid: true,
    sno: 10,
    errorMessage: "",
    inputType: "text",
    typeuser: "1",
    label: "Collage Name",
    placeholder: "Enter Collage Name",
    value: "",
    required: false,
    helpertext: "Max 50 characters allowed",
    maxCharacters: 50
  },
  {
    valid: true,
    sno: 11,
    errorMessage: "",
    inputType: "text",
    typeuser: "1",
    label: "Insititue Name",
    placeholder: "Enter Insititue Name",
    value: "",
    required: false,
    helpertext: "Max 50 characters allowed",
    maxCharacters: 50
  },
  {
    valid: true,
    sno: 12,
    errorMessage: "",
    inputType: "text",
    typeuser: "1",
    label: "University Name",
    placeholder: "Enter University Name",
    value: "",
    required: false,
    helpertext: "Max 50 characters allowed",
    maxCharacters: 50
  },
  {
    valid: true,
    sno: 13,
    errorMessage: "",
    inputType: "number",
    typeuser: "1",
    label: "Postal Code",
    placeholder: "Enter Postal Code",
    value: "",
    required: false,
    helpertext: "Max 10 numbers are allowed",
    maxCharacters: 10
  },
  {
    valid: true,
    sno: 14,
    errorMessage: "",
    inputType: "text",
    typeuser: "1",
    label: "Course Name",
    placeholder: "Enter Course Name",
    value: "",
    required: false,
    helpertext: "Max 30 characters allowed",
    maxCharacters: 30
  },
  {
    valid: true,
    sno: 15,
    errorMessage: "",
    inputType: "number",
    typeuser: "1",
    label: "Course Duration",
    placeholder: "Enter Course Duration",
    value: "",
    required: false,
    helpertext: "Only numbers allowed. E.g., 2.",
    maxCharacters: 2
  },
  {
    valid: true,
    sno: 16,
    errorMessage: "",
    inputType: "number",
    typeuser: "1",
    label: "Course Pursuing Year",
    placeholder: "Enter Course Pursuin Year",
    value: "",
    required: false,
    helpertext: "Only numbers allowed. E.g., 2.",
    maxCharacters: 2
  },
  {
    valid: true,
    sno: 17,
    errorMessage: "",
    inputType: "text",
    typeuser: "1",
    label: "Parent / Guardian Name",
    placeholder: "Enter Parent / Guardian Name",
    value: "",
    required: false,
    helpertext: "Max 30 characters allowed",
    maxCharacters: 30
  },
  {
    valid: true,
    sno: 18,
    errorMessage: "",
    inputType: "phone num",
    typeuser: "1",
    label: "Parent / Guardian Number",
    placeholder: "Enter Parent / Guardian Number",
    value: "",
    required: false,
  },
  {
    valid: true,
    sno: 19,
    errorMessage: "",
    inputType: "textarea",
    typeuser: "1",
    label: "Long Term Goal",
    placeholder: "Enter Your Long Term Goal",
    value: "",
    required: false,
    helpertext: "Max 1500 characters allowed",
    maxCharacters: 1500
  },
  {
    valid: true,
    sno: 20,
    errorMessage: "",
    inputType: "textarea",
    typeuser: "1",
    label: "Short Term Goal",
    placeholder: "Enter Your Short term Goal",
    value: "",
    required: false,
    helpertext: "Max 1500 characters allowed",
    maxCharacters: 1500
  },
  {
    valid: true,
    sno: 21,
    errorMessage: "",
    inputType: "textarea",
    typeuser: "1",
    label: "Address",
    placeholder: "Enter Your Address",
    value: "",
    required: false,
    helpertext: "Max 50 characters allowed",
    maxCharacters: 50
  },
  {
    valid: true,
    sno: 22,
    errorMessage: "",
    inputType: "textarea",
    typeuser: "1",
    label: "Parent / Guardian Addresss",
    placeholder: "Enter Parent / Guardian Addresss",
    value: "",
    required: false,
    helpertext: "Max 50 characters allowed",
    maxCharacters: 50
  },
  {
    valid: true,
    sno: 8,
    errorMessage: "",
    inputType: "text",
    typeuser: "2",
    label: "Company name",
    placeholder: "Enter Company name",
    value: "",
    required: false,
    helpertext: "Max 30 characters allowed",
    maxCharacters: 30
  },
  {
    valid: true,
    sno: 9,
    errorMessage: "",
    inputType: "text",
    typeuser: "2",
    label: "CEO name",
    placeholder: "Enter CEO name",
    value: "",
    required: false,
    helpertext: "Max 30 characters allowed",
    maxCharacters: 30
  },
  {
    valid: true,
    sno: 10,
    errorMessage: "",
    inputType: "text",
    typeuser: "2",
    label: "Company website",
    placeholder: "Enter Company website",
    value: "",
    required: false,
    helpertext: "Max 30 characters allowed",
    maxCharacters: 30
  },
  {
    valid: true,
    sno: 11,
    errorMessage: "",
    inputType: "text",
    typeuser: "2",
    label: "Industry name",
    placeholder: "Enter Industry name",
    value: "",
    required: false,
    helpertext: "Max 30 characters allowed",
    maxCharacters: 30
  },
  {
    valid: true,
    sno: 12,
    errorMessage: "",
    inputType: "text",
    typeuser: "2",
    label: "Contact person",
    placeholder: "Enter Contact person",
    value: "",
    required: false,
    helpertext: "Max 30 characters allowed",
    maxCharacters: 30
  },
  {
    valid: true,
    sno: 13,
    errorMessage: "",
    inputType: "text",
    typeuser: "2",
    label: "Founder name",
    placeholder: "Enter Founder name",
    value: "",
    required: false,
    helpertext: "Max 30 characters allowed",
    maxCharacters: 30
  },
  {
    valid: true,
    sno: 14,
    errorMessage: "",
    inputType: "number",
    typeuser: "2",
    label: "No. of employees",
    placeholder: "Enter No. of employees",
    value: "",
    required: false,
    helpertext: "Only numbers allowed. E.g., 20.",
    maxCharacters: 2
  },
  {
    valid: true,
    sno: 15,
    errorMessage: "",
    inputType: "text",
    typeuser: "2",
    label: "No. of branch",
    placeholder: "Enter No. of branch",
    value: "",
    required: false,
    helpertext: "Only numbers allowed. E.g., 30.",
    maxCharacters: 2
  },
  {
    valid: true,
    sno: 16,
    errorMessage: "",
    inputType: "textarea",
    typeuser: "2",
    label: "Company Address",
    placeholder: "Enter Company Address",
    value: "",
    required: false,
    helpertext: "Max 50 characters allowed",
    maxCharacters: 50
  },
]